user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  helpers:
    gravatar:
      size: 100
    post_per_page: 10
  index:
    per_page: 10
micropost:
  content:
    max_length: 160
  gravatar:
    size: 50
